version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt pylint
      - yum update -y
      - yum install -y jq
  pre_build:
    commands:
      - python --version
      - pip show django
      - python manage.py collectstatic --noinput
      - pylint rentacar/**/*.py || true
  build:
    commands:
      - echo "DONE!!!!"
artifacts:
   files:
    - '**/*'