version: 0.2
env:
  secrets-manager:
    LOGIN: prod/sonar/x23302712/rentacar:sonartoken
    HOST: prod/sonar/x23302712/rentacar:HOST
    Organization: prod/sonar/x23302712/rentacar:Organization
    Project: prod/sonar/x23302712/rentacar:Project
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt pylint
      - yum update -y
      - yum install -y jq
  pre_build:
    commands:
      - python --version
      - python manage.py collectstatic --noinput
      - pylint rentacar/**/*.py || true
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:./sonar-scanner-3.3.0.1492-linux/bin/
  build:
    commands:
      - sonar-scanner -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization || true
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
      - cat result.json
#      - if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then export CODEBUILD_BUILD_SUCCEEDING=0; fi
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
artifacts:
   files:
    - '**/*'